version: '3.9'
services:
  auth:
    build:
      dockerfile: ./apps/auth/Dockerfile
      target: development
      context: .
    command: sh -c "npm run serve:auth"
    env_file:
     - ./apps/auth/.env
    expose:
      - 3001
    ports:
      - "4001:3001"
      - "9010:9669"
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  accounting:
    build:
      dockerfile: ./apps/accounting/Dockerfile
      target: development
      context: .
    command: sh -c "npm run serve:accounting"
    expose:
      - 3002
    ports:
      - "4020:3002"
      - "9020:9669"
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    logging:
      options:
        max-size: 1g
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ~/deps-storage/mongo_volume:/data/db

  redis:
    image: redis:latest
    expose:
      - "6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    container_name: redis
    restart: always
    volumes:
      - ~/deps-storage/redis_volume:/var/lib/redis
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6379:6379

networks:
  default:
    name: example_dev_network
    driver: bridge
